blank_issues_enabled: false
contact_links:
  - name: â“ Community-driven support
    url: https://docs.mailcow.email/#get-support
    about: Please use the community forum for questions or assistance
  - name: ğŸš¨ Report a security vulnerability
    url: https://www.servercow.de/anfrage?lang=en
    about: Please give us appropriate time to verify, respond and fix before disclosure.
