blank_issues_enabled: false
contact_links:
  - name: â“ Community-driven support (Free)
    url: https://docs.mailcow.email/#community-support-and-chat
    about: Please use the community forum for questions or assistance
  - name: ğŸ”¥ Premium Support (Paid)
    url: https://www.servercow.de/mailcow?lang=en#support
    about: Buy a support subscription for any critical issues and get assisted by the mailcow Team. See conditions!
  - name: ğŸš¨ Report a security vulnerability
    url: "mailto:info@servercow.de?subject=mailcow: dockerized Security Vulnerability"
    about: Please give us appropriate time to verify, respond and fix before disclosure.
